// Login Types

export const START_LOGIN = 'START_LOGIN';
export const IS_LOGIN_PAGE_LOADING = 'IS_LOGIN_PAGE_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_RESET = 'LOGIN_RESET';

// favorite books types
export const START_FAVORITE_BOOKS = 'START_FAVORITE_BOOKS';
export const FAVORITE_BOOKS_SUCCESS = 'FAVORITE_BOOKS_SUCCESS';
export const FAVORITE_BOOKS_FAILED = 'FAVORITE_BOOKS_FAILED';
export const FAVORITE_BOOKS_ERROR = 'FAVORITE_BOOKS_ERROR';
export const FAVORITE_BOOKS_RESET = 'FAVORITE_BOOKS_RESET';
